# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
# TODO: Naming convention'a bak bunun için
name: next-shopper-development

services:
  # TODO: Mesela bunun adı db-1 oluyor. başka bir db isimli service olunca conflict oluyor mu?
  # Ya da container_name kullanmak mı lazım vs vs.
  db:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # TODO: Naming convention'a bak bunun için
      POSTGRES_DB: dev-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
